#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := actuator_LED_controller
EXTRA_COMPONENT_DIRS := components

include $(IDF_PATH)/make/project.mk

